# Generated by Django 4.0.1 on 2022-02-09 14:55

from django.db import migrations, models
import tab.models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file_path',
            field=models.FileField(upload_to=tab.models.Application._set_file_path, validators=[tab.models.Application._validate_file]),
        ),
    ]
