# Generated by Django 4.0.2 on 2022-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_alter_application_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='postimages'),
        ),
    ]
