# Generated by Django 4.0.1 on 2022-01-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_applications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='subject',
            new_name='path',
        ),
        migrations.AddField(
            model_name='applications',
            name='name',
            field=models.CharField(default=None, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='phonenumber',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='studentnumber',
            field=models.CharField(default='null', max_length=16),
            preserve_default=False,
        ),
    ]
