# Generated by Django 4.0.1 on 2022-01-26 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0003_rename_subject_applications_path_applications_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 2, 53, 13, 595358)),
            preserve_default=False,
        ),
    ]
