# Generated by Django 4.0.1 on 2022-01-27 21:06

from django.db import migrations, models
import tab.models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0004_applications_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='path',
            field=models.FileField(upload_to='applications/%Y-%m', validators=[tab.models.Applications._validate_file]),
        ),
    ]
